services:
  ui_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://api.necilcakmak.com
    image: necilcakmak/blog:ui
    container_name: ui_container
    restart: always
    networks:
      - blog_network

networks:
  blog_network:
    external: true
